---
- name: bootstrap server
  hosts: all
  gather_facts: no
  roles:
    - ansible-prereqs
    #- package-repos
    - sudo
    - localize
    - firewalled
    - { role: nickjj.fail2ban, become: true, tags: fail2ban }
