---
- name: core server setup
  hosts: core
  gather_facts: yes
  vars_files:
    - datadog_api_key.yml
    - datadog-checks.yml
  roles:
    - docker-prereqs
    - { role: dochang.docker, become: true }
    - users
    - { role: Datadog.datadog, become: true }
    - java
    - jenkins

  tasks:
    - name: Make sure datadog agent has docker access
      user:
        name: dd-agent
        groups: docker
        append: yes
      become: true

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
