ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.require_version ">= 1.8.1"

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_version = ">= 8.3, < 8.4"

  config.vm.define "devmain", primary: true do |config|
	config.vm.network "private_network", ip: "192.168.60.2"
	config.vm.network "forwarded_port", guest: 22, host: 2262, auto_correct: false
    config.vm.hostname = "devmain"
  end

  config.vm.define "localmain" do |config|
	config.vm.network "private_network", ip: "192.168.50.2"
	config.vm.network "forwarded_port", guest: 22, host: 2252, auto_correct: false
    config.vm.hostname = "localmain"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 3072
	vb.cpus = 2
	vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end
end
