
# http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread/27341847#27341847
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=744145
# http://everythingshouldbevirtual.com/ansible-debian-based-gotchas-part-1

- name: uninstall python-pip (If installed) - Debian (and Ubuntu)
  apt:
    name: python-pip
    state: absent
  when: ansible_os_family == "Debian"

- name: install python-setuptools to get easy_install - Debian (and Ubuntu)
  apt:
    name: python-setuptools
    state: present
  when: ansible_os_family == "Debian"

- name: debian | installing python packages
  easy_install:
    name: "{{ item }}"
    state: present
  with_items:
    - pip
  when: ansible_os_family == "Debian"

# https://github.com/DataDog/docker-dd-agent/pull/181/commits/d140d2797a3252b51f69b891246ebe37d637e28b
- name: Add cgroup stuff (cgroup_enable=memory swapaccount=1)
  lineinfile:
    dest: "/etc/default/grub"
    regexp: '(^GRUB_CMDLINE_LINUX_DEFAULT="((?!cgroup_enable=memory swapaccount=1)[\w=\/\-\\.]*\s?)*)"$'
    line: '\1 cgroup_enable=memory swapaccount=1"'
    backrefs: yes
    state: present
  register: grubfile

- name: update grub
  command: update-grub
  when: grubfile.changed
