- name: Jessie backports deb repository (with Java)
  apt_repository:
    repo: deb http://httpredir.debian.org/debian jessie-backports main contrib non-free
    state: present
  become: true
  register: backports_repo

- name: Update apt cache
  apt:
    update_cache: yes
  when: backports_repo.changed
  become: true

#- apt_key:
#    url: "https://pkg.jenkins.io/debian/jenkins.io.key"
#    state: present
#  become: true

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851667
#  apt:
#    name: ca-certificates-java
#    state: present
#  become: true

# Need to pass -t jessie-backports to apt
- name: Install ca-certs-java
  shell: DEBIAN_FRONTEND=noninteractive apt install -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -t jessie-backports ca-certificates-java
  become: true

- name: Install jre
  apt:
    name: openjdk-8-jre-headless
    state: present
  become: true
