- user:
    name: kjetiljd
    update_password: on_create
    password: "{{ kjetiljd_pwd|password_hash('sha512') }}"
    shell: /bin/bash
    group: staff
    groups: sudo,docker
    append: yes

- user:
    name: theo2000
    update_password: on_create
    password: "{{ theo2000_pwd|password_hash('sha512') }}"
    shell: /bin/bash
    group: users
    groups: docker
    append: yes

- name: Create www group
  group:
    name: www

- name: Create deployment-user for travis
  user:
    name: deploy
    shell: /bin/bash
    group: users
    groups: www
    append: yes
    home: /var/deploy

- name: Set authorized key took from file
  authorized_key:
    user: deploy
    key: "{{ item }}"
  with_file:
    - keys/deploy_rsa.pub
